# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2944109cdea376963495f7456126b5a9b69ce9b99c806ec3929749beaa3e5dfd25f54c448fa4a646b0d8d7bd481db4698822f53bdf5bdbad7477e20145d4d2e9

test:
  secret_key_base: 75ba1187c6c860ed41b40f3ff402207cbf8ebb6640b2fcb00c764cefa8df7500178ff15ad6c702812dd9ae41a1fc4349f53e383eea9a5ab61e2ea366678b2e70

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
